/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.31
 * Generated at: 2022-12-12 09:29:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/C:/Users/Loc0u/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar", Long.valueOf(1669027854996L));
    _jspx_dependants.put("jar:file:/C:/Users/Loc0u/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153374282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; ISO-8859-1;charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<title>Santun liikuntakeskus</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css\" />\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1>Santun liikuntakeskuksen etusivu</h1>\r\n");
      out.write("\t<p> <a href=\"/listaa-ryhmaliikunnat\">Ryhmäliikuntalista</a></p>\r\n");
      out.write("\t<p>\t<a href=\"/hallintapaneeli\">Hallintapaneeli</a></p>\r\n");
      out.write("\t<p>\r\n");
      out.write("\tHarjoitustyön aiheena on kuvitteellinen Santun liikuntakeskus, jonka tarjontaan kuuluu useita erilaisia\r\n");
      out.write("\tryhmäliikuntatunteja.\r\n");
      out.write("\t</p>\r\n");
      out.write("\t<p>\r\n");
      out.write("\t<b>Toiminnallisuudet:</b>\t\r\n");
      out.write("\t</p>\r\n");
      out.write("\t<p>\r\n");
      out.write("\tHallintapaneeli - sisältää kaikki sovelluksen toiminnallisuudet.\t\r\n");
      out.write("\t</p>\r\n");
      out.write("\t<p>\r\n");
      out.write("\tRyhmäliikuntalista - kaikki tarjolla olevat ryhmäliikunnat listattu tietoineen.\r\n");
      out.write("\t<p>\r\n");
      out.write("\tRyhmäliikuntalistan muokkaa-painike - avaa valitun ryhmänliikunnan tiedot ja asettaa ne muokkauslomakkeeseen.\r\n");
      out.write("\t</p>\r\n");
      out.write("\t<p>\r\n");
      out.write("\tRyhmäliikuntalistan poista-painike - poistaa suoraan valitun ryhmäliikunnan.\r\n");
      out.write("\t</p>\r\n");
      out.write("\t<p>\r\n");
      out.write("\tLisää ryhmäliikunta id:llä - ryhmäliikunnan lisäys id:n avulla, jotta tietokantaan voidaan lisätä tietoa mihin kohtaan tahansa.\r\n");
      out.write("\t</p>\r\n");
      out.write("\t<p>\r\n");
      out.write("\tLisää ryhmäliikunta ilman id:tä - ryhmäliikunnan lisäys ilman id:tä, jolloin uusi tieto menee tietokannassa viimeiseksi.\r\n");
      out.write("\t</p>\r\n");
      out.write("\t<p>\r\n");
      out.write("\tMuokkaa ryhmäliikunta - erillinen lomake, jonka avulla haluttua ryhmäliikuntaa voidaan muokata.\r\n");
      out.write("\t</p>\r\n");
      out.write("\t<p>\r\n");
      out.write("\tPoista ryhmäliikunta - erillinen lomake, jonka avulla haluttu ryhmäliikunta voidaan poistaa id:n avulla.\r\n");
      out.write("\t</p>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
